services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    image: frontend:latest
    #
    ports:
      - "8080:80"
    restart: unless-stopped
    
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    image: backend:latest
    #
    ports:
      - "8000:8000"
    restart: unless-stopped
